# Read and process a directory of log files generated by HyGen CMS.
#   Thanks to Herb Hainey for some source code contributions.

import os
import glob

verbose = True  # Switch dev print statements on and off
log_path = '/Users/billmarty/CMSlogs'

def main():

    # Go to the log directory and get a list of the 'run' log files.
    os.chdir(log_path)
    if verbose: print('Working dir: ' + str(os.getcwd()))
    run_files = glob.glob("*run*.csv")
    if verbose: print('There are ' + str(len(run_files)) + ' run log files.')
    run_files.sort()

    # File name template: year-month-day_hour_run#.csv
    # Get a list of the dates.
    date_list = []
    for file in run_files:
        if '_' in file:
            underscore = file.find('_')
            file_date = file[:underscore]
            if not file_date in date_list:
                date_list.append(file_date)
    if verbose:
        print(str(len(date_list)) + ' unique dates')
        print(date_list)
        print('Most recent date is: ' + str(date_list[-1]))

    # Let's start with the run files for the most recent date.
    # In theory, run_files is already a sorted by date.
    recent_date_files = []
    while date_list[-1] in run_files[-1]:
        recent_date_files.append(run_files.pop())
    recent_date_files.reverse()
    if verbose:
        print(str(len(recent_date_files)) + ' recent date files')
        print(recent_date_files)




if __name__ == '__main__':
    main()
